# Generated by Django 5.1.5 on 2025-03-26 03:02

import mysite.storage_backends
import toolhub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0002_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=mysite.storage_backends.MediaStorage(), upload_to=toolhub.models.upload_to_item),
        ),
    ]
