# Generated by Django 5.1.6 on 2025-03-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
