# Generated by Django 4.2.20 on 2025-03-18 05:52

from django.db import migrations, models
import toolhub.models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=toolhub.models.CustomUser.default_profile_picture, null=True, upload_to=toolhub.models.upload_to_profile),
        ),
    ]
