# Generated by Django 5.1.6 on 2025-03-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
