# Generated by Django 5.1.5 on 2025-03-26 03:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0003_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
