# Generated by Django 5.1.5 on 2025-03-27 18:42

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0004_collection_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this private collection (librarians can always access).', related_name='shared_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
