# Generated by Django 5.1.5 on 2025-03-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0005_collection_allowed_users_alter_collection_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='identifier',
            field=models.CharField(default='default', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('main_warehouse', 'Main Warehouse'), ('aux_warehouse', 'Aux Warehouse'), ('patrons_location', 'Patrions Location'), ('remote_storage', 'Remote Storage')], default='main_warehouse', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('currently_borrowed', 'Currently Borrowed'), ('being_repaired', 'Being Repaired'), ('lost', 'Lost'), ('archived', 'Archived')], default='available', max_length=50),
        ),
    ]
