# Generated by Django 4.2.19 on 2025-04-17 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0006_item_description_item_identifier_item_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('main_warehouse', 'Main Warehouse'), ('aux_warehouse', 'Aux Warehouse'), ('patrons_location', 'Patrons Location'), ('remote_storage', 'Remote Storage')], default='main_warehouse', max_length=50),
        ),
    ]
