# Generated by Django 5.1.6 on 2025-04-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0007_customuser_join_date_alter_item_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='return_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='borrowrequest',
            unique_together={('item', 'user', 'status')},
        ),
    ]
