# Generated by Django 5.1.6 on 2025-04-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0008_borrowrequest_return_due_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowrequest',
            unique_together={('item', 'user')},
        ),
    ]
