# Generated by Django 5.1.6 on 2025-04-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0009_alter_borrowrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
