# Generated by Django 5.1.6 on 2025-04-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0007_item_borrower_alter_item_location'),
        ('toolhub', '0010_borrowrequest_note'),
    ]

    operations = [
    ]
