# Generated by Django 5.1.5 on 2025-04-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0011_merge_20250417_1143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('main_warehouse', 'Main Warehouse'), ('aux_warehouse', 'Aux Warehouse'), ('patrons_location', "Patron's Location"), ('remote_storage', 'Remote Storage')], default='main_warehouse', max_length=50),
        ),
    ]
