# Generated by Django 5.1.5 on 2025-04-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0012_alter_borrowrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('returned_on_time', 'Returned On Time'), ('returned_overdue', 'Returned Late')], default='pending', max_length=20),
        ),
    ]
