# Generated by Django 5.1.5 on 2025-04-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0013_alter_borrowrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('currently_borrowed', 'Currently Borrowed'), ('currently_requested', 'Currently Requested'), ('being_repaired', 'Being Repaired'), ('lost', 'Lost'), ('archived', 'Archived')], default='available', max_length=50),
        ),
    ]
