# Generated by Django 5.1.5 on 2025-04-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0014_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('currently_borrowed', 'Currently Borrowed'), ('currently_requested', 'Already Requested'), ('being_repaired', 'Being Repaired'), ('lost', 'Lost'), ('archived', 'Archived')], default='available', max_length=50),
        ),
    ]
