# Generated by Django 5.1.6 on 2025-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0015_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='borrow_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
